package model.BreakDownPaper.AM;

import model.BreakDownPaper.AM.common.PwcOdmBreakDownPaperAM;

import model.BreakDownPaper.VO.PwcOdmBreakDownHdrVOImpl;
import model.BreakDownPaper.VO.PwcOdmBreakDownWarpCountVOImpl;

import model.BreakDownPaper.VO.PwcOdmBreakDownWeftCountVOImpl;

import oracle.jbo.Row;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 29 01:57:03 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcOdmBreakDownPaperAMImpl extends ApplicationModuleImpl implements PwcOdmBreakDownPaperAM {
    /**
     * This is the default constructor (do not remove).
     */
    public PwcOdmBreakDownPaperAMImpl() {
    }

    /**
     * Container's getter for PwcOdmBreakDownHdrVO1.
     * @return PwcOdmBreakDownHdrVO1
     */
    public PwcOdmBreakDownHdrVOImpl getPwcOdmBreakDownHdrVO1() {
        return (PwcOdmBreakDownHdrVOImpl)findViewObject("PwcOdmBreakDownHdrVO1");
    }

    /**
     * Container's getter for PwcOdmBreakDownWarpCountVO1.
     * @return PwcOdmBreakDownWarpCountVO1
     */
    public PwcOdmBreakDownWarpCountVOImpl getPwcOdmBreakDownWarpCountVO1() {
        return (PwcOdmBreakDownWarpCountVOImpl)findViewObject("PwcOdmBreakDownWarpCountVO1");
    }

    /**
     * Container's getter for PwcOdmBreakDownHeaderWarpCountVL1.
     * @return PwcOdmBreakDownHeaderWarpCountVL1
     */
    public ViewLinkImpl getPwcOdmBreakDownHeaderWarpCountVL1() {
        return (ViewLinkImpl)findViewLink("PwcOdmBreakDownHeaderWarpCountVL1");
    }

    /**
     * Container's getter for PwcOdmBreakDownWeftCountVO1.
     * @return PwcOdmBreakDownWeftCountVO1
     */
    public PwcOdmBreakDownWeftCountVOImpl getPwcOdmBreakDownWeftCountVO1() {
        return (PwcOdmBreakDownWeftCountVOImpl)findViewObject("PwcOdmBreakDownWeftCountVO1");
    }

    /**
     * Container's getter for PwcOdmBreakDownHeaderWeftCountVL1.
     * @return PwcOdmBreakDownHeaderWeftCountVL1
     */
    public ViewLinkImpl getPwcOdmBreakDownHeaderWeftCountVL1() {
        return (ViewLinkImpl)findViewLink("PwcOdmBreakDownHeaderWeftCountVL1");
    }
    
    public void warpDialogListener(){
        ViewObject warpVO = this.getPwcOdmBreakDownWarpCountVO1();
        ViewObject HeaderVo = null;
        RowSetIterator warpRowSet = warpVO.createRowSetIterator("warpRowSet");
        Row row = null;
        String TransCountPlyResult = null;
        String Type = null;
        String Brand = null;
        String Blend = null;
        String Lot = null;
        while(warpRowSet.hasNext()){
            row = warpRowSet.next();       
            try{
                if(TransCountPlyResult == null)
                    TransCountPlyResult = row.getAttribute("TransCountPlyResult").toString();
                else
                    TransCountPlyResult = TransCountPlyResult +"+"+row.getAttribute("TransCountPlyResult").toString(); 
            }catch(NullPointerException e){
                ;
            }
            try{
                if(Type == null)
                    Type = row.getAttribute("Type").toString()+",";
                else
                    Type = Type+row.getAttribute("Type").toString()+",";
            }catch(NullPointerException e){
                ;
            }
            try{
                if(Brand == null)
                    Brand = row.getAttribute("Brand").toString()+",";
                else
                    Brand = Brand+row.getAttribute("Brand").toString()+",";
            }catch(NullPointerException e){
                ;
            }
            try{
                if(Blend == null)
                    Blend = row.getAttribute("Blend").toString()+",";
                else
                    Blend = Blend+row.getAttribute("Blend").toString()+",";
            }catch(NullPointerException e){
                ;
            }
            try{
                if(Lot == null)
                Lot = row.getAttribute("Lot").toString()+",";
                else
                Lot = Lot+row.getAttribute("Lot").toString()+",";
                    
            }catch(NullPointerException e){
                ;
            }
        }
        warpRowSet.closeRowSetIterator();
        TransCountPlyResult = "("+TransCountPlyResult+")";
        HeaderVo = this.getPwcOdmBreakDownHdrVO1();
        HeaderVo.getCurrentRow().setAttribute("Constraction1", TransCountPlyResult);
        try{
            HeaderVo.getCurrentRow().setAttribute("WarpYarnCount", TransCountPlyResult); 
        }catch(NumberFormatException e){
            ;    
        }
        HeaderVo.getCurrentRow().setAttribute("YarnType", Type);  
        HeaderVo.getCurrentRow().setAttribute("YarnBrand", Brand); 
        HeaderVo.getCurrentRow().setAttribute("YarnBlend", Blend); 
        HeaderVo.getCurrentRow().setAttribute("YarnLot", Lot); 
    }
    
    
    public void weftDialogListener(){
        ViewObject weftVO = this.getPwcOdmBreakDownWeftCountVO1();
        ViewObject HeaderVo = null;
        RowSetIterator weftRowSet = weftVO.createRowSetIterator("weftRowSet");
        Row row = null;
        String TransCountPly = null;
        String Type = null;
        String Brand = null;
        String Blend = null;
        String Lot = null;
        while(weftRowSet.hasNext()){
            row = weftRowSet.next();       
            try{
                if(TransCountPly == null){
                    TransCountPly = row.getAttribute("TransCountPly").toString();
                }
                else{
                    TransCountPly = TransCountPly +"+"+row.getAttribute("TransCountPly").toString();
                }    
            }catch(NullPointerException e){
                ;
            }
            try{
                if(Type==null){
                    Type = row.getAttribute("Type").toString()+",";
                }else{
                    Type = Type+row.getAttribute("Type").toString()+",";
                }
            }catch(NullPointerException e){
                ;
            }
            try{
                if(Brand == null){
                    Brand = row.getAttribute("Brand").toString()+",";
                }else{
                    Brand = Brand+row.getAttribute("Brand").toString()+",";
                }
            }catch(NullPointerException e){
                ;
            }
            try{
                if(Blend == null){
                    Blend = row.getAttribute("Blend").toString()+",";
                }else{
                    Blend = Blend+row.getAttribute("Blend").toString()+",";
                }
                
            }catch(NullPointerException e){
                ;
            }
            try{
                if(Lot == null){
                    Lot = row.getAttribute("Lot").toString()+",";    
                }
                else{
                    Lot = Lot+row.getAttribute("Lot").toString()+",";
                }
            }catch(NullPointerException e){
                ;
            }
        }
        weftRowSet.closeRowSetIterator();
        TransCountPly = "("+TransCountPly+")";
        HeaderVo = this.getPwcOdmBreakDownHdrVO1();
        HeaderVo.getCurrentRow().setAttribute("Contraction2", TransCountPly);
        HeaderVo.getCurrentRow().setAttribute("WeftCount", TransCountPly);
        HeaderVo.getCurrentRow().setAttribute("WeftYarnType", Type);
        HeaderVo.getCurrentRow().setAttribute("WeftYarnBrand", Brand);
        HeaderVo.getCurrentRow().setAttribute("WeftYarnBlend", Blend);
    }


    /**
     * Container's getter for PwcOdmBreakDownPileCountVO1.
     * @return PwcOdmBreakDownPileCountVO1
     */
    public ViewObjectImpl getPwcOdmBreakDownPileCountVO1() {
        return (ViewObjectImpl)findViewObject("PwcOdmBreakDownPileCountVO1");
    }

    /**
     * Container's getter for PwcOdmBreakDownHeaderPileCountVL1.
     * @return PwcOdmBreakDownHeaderPileCountVL1
     */
    public ViewLinkImpl getPwcOdmBreakDownHeaderPileCountVL1() {
        return (ViewLinkImpl)findViewLink("PwcOdmBreakDownHeaderPileCountVL1");
    }
    
    public void pileYarnCountDialogListener(){
        
        ViewObject pileVO = this.getPwcOdmBreakDownPileCountVO1();
        ViewObject HeaderVo = null;
        RowSetIterator pileRowSet = pileVO.createRowSetIterator("pileRowSet");
        Row row = null;
        String TransCountPly = null;
        String Type = null;
        String Brand = null;
        String Blend = null;
        String Lot = null;
        while(pileRowSet.hasNext()){
            row = pileRowSet.next();       
            try{
                if(TransCountPly == null)
                    TransCountPly = row.getAttribute("TransCountPly").toString();
                else
                    TransCountPly = TransCountPly +"+"+row.getAttribute("TransCountPly").toString();
                
            }catch(NullPointerException e){
                ;
            }
            /*
            try{
                Type = Type+row.getAttribute("Type").toString()+",";
            }catch(NullPointerException e){
                ;
            }
            */
            try{
                if(Brand == null)
                    Brand = row.getAttribute("Brand").toString()+",";
                else 
                    Brand = Brand+row.getAttribute("Brand").toString()+",";
            }catch(NullPointerException e)
            {
                ;
            }
            /*
            try{
                Blend = Type+row.getAttribute("Blend").toString()+",";
            }catch(NullPointerException e){
                ;
            }
            try{
                Lot = Type+row.getAttribute("Lot").toString()+",";
            }catch(NullPointerException e){
                ;
            }
            */
        }
        pileRowSet.closeRowSetIterator();
        TransCountPly = "("+TransCountPly+")";
        HeaderVo = this.getPwcOdmBreakDownHdrVO1();
        HeaderVo.getCurrentRow().setAttribute("PileYarnCount", TransCountPly);
        HeaderVo.getCurrentRow().setAttribute("PileYarnBrand", TransCountPly);
        //HeaderVo.getCurrentRow().setAttribute("WeftCount", TransCountPly);
        //HeaderVo.getCurrentRow().setAttribute("WeftYarnType", Type);
        //HeaderVo.getCurrentRow().setAttribute("WeftYarnBrand", Brand);
        //HeaderVo.getCurrentRow().setAttribute("WeftYarnBlend", Blend);
        
    }

    /**
     * Container's getter for PwcOdmBreakDownCountFactsVO1.
     * @return PwcOdmBreakDownCountFactsVO1
     */
    public ViewObjectImpl getPwcOdmBreakDownCountFactsVO1() {
        return (ViewObjectImpl)findViewObject("PwcOdmBreakDownCountFactsVO1");
    }

    /**
     * Container's getter for PwcOdmBreakDownHdrCountFactsVL1.
     * @return PwcOdmBreakDownHdrCountFactsVL1
     */
    public ViewLinkImpl getPwcOdmBreakDownHdrCountFactsVL1() {
        return (ViewLinkImpl)findViewLink("PwcOdmBreakDownHdrCountFactsVL1");
    }
}
