package model.GradingWeaving.AM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 09 04:09:24 EDT 2017
// ---------------------------------------------------------------------
public interface PwcOdmGradingWeavingAM extends ApplicationModule {
    void Exceed_TOTALQTY();
}
