package model.BreakDownPaper.AM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 03 00:08:17 PKT 2017
// ---------------------------------------------------------------------
public interface PwcOdmBreakDownPaperAM extends ApplicationModule {
    void warpDialogListener();

    void weftDialogListener();

    void pileYarnCountDialogListener();
}
