package model.BreakDownPaper.EO;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 29 01:52:53 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcOdmBreakDownHdrEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HeaderId {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getHeaderId();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        GdNumber {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getGdNumber();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setGdNumber((String)value);
            }
        }
        ,
        SaleOrderNumber {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getSaleOrderNumber();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setSaleOrderNumber((Number)value);
            }
        }
        ,
        ItemId {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getItemId();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setItemId((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getOrgId();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        Constraction1 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getConstraction1();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setConstraction1((String)value);
            }
        }
        ,
        Contraction2 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getContraction2();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setContraction2((String)value);
            }
        }
        ,
        Contraction3 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getContraction3();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setContraction3((Number)value);
            }
        }
        ,
        Contraction4 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getContraction4();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setContraction4((Number)value);
            }
        }
        ,
        GreigeWidth {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getGreigeWidth();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setGreigeWidth((Number)value);
            }
        }
        ,
        FinishWidth {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getFinishWidth();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setFinishWidth((Number)value);
            }
        }
        ,
        OrderQtyYds {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getOrderQtyYds();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setOrderQtyYds((Number)value);
            }
        }
        ,
        OrderQtyMtr {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getOrderQtyMtr();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setOrderQtyMtr((Number)value);
            }
        }
        ,
        LastDeliveryDate {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getLastDeliveryDate();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setLastDeliveryDate((Date)value);
            }
        }
        ,
        Blend {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getBlend();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setBlend((String)value);
            }
        }
        ,
        ProcessLoss {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getProcessLoss();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setProcessLoss((Number)value);
            }
        }
        ,
        BeamWidth {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getBeamWidth();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setBeamWidth((String)value);
            }
        }
        ,
        LoomType {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getLoomType();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setLoomType((String)value);
            }
        }
        ,
        BeamDiaMm {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getBeamDiaMm();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setBeamDiaMm((Number)value);
            }
        }
        ,
        ReqSizeLength {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getReqSizeLength();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setReqSizeLength((Number)value);
            }
        }
        ,
        NumberBeam {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getNumberBeam();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setNumberBeam((Number)value);
            }
        }
        ,
        WtOfWarp {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getWtOfWarp();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setWtOfWarp((Number)value);
            }
        }
        ,
        TotalEnds {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getTotalEnds();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setTotalEnds((Number)value);
            }
        }
        ,
        WarpingStartDate {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getWarpingStartDate();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setWarpingStartDate((Date)value);
            }
        }
        ,
        YarnBrand {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getYarnBrand();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setYarnBrand((String)value);
            }
        }
        ,
        YarnLot {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getYarnLot();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setYarnLot((String)value);
            }
        }
        ,
        YarnType {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getYarnType();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setYarnType((String)value);
            }
        }
        ,
        YarnBlend {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getYarnBlend();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setYarnBlend((String)value);
            }
        }
        ,
        BeamLength {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getBeamLength();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setBeamLength((String)value);
            }
        }
        ,
        TotalWarpReq {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getTotalWarpReq();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setTotalWarpReq((Number)value);
            }
        }
        ,
        WarpingFinishingDate {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getWarpingFinishingDate();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setWarpingFinishingDate((Date)value);
            }
        }
        ,
        DropperThicknessMm {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getDropperThicknessMm();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setDropperThicknessMm((Number)value);
            }
        }
        ,
        GreyEpiWeaving {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getGreyEpiWeaving();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setGreyEpiWeaving((Number)value);
            }
        }
        ,
        ReedCount {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getReedCount();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setReedCount((Number)value);
            }
        }
        ,
        EndDent {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getEndDent();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setEndDent((Number)value);
            }
        }
        ,
        SelvedgeEndsBothSides {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getSelvedgeEndsBothSides();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setSelvedgeEndsBothSides((Number)value);
            }
        }
        ,
        SelvedgeSize {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getSelvedgeSize();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setSelvedgeSize((Number)value);
            }
        }
        ,
        PlanLoom {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getPlanLoom();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setPlanLoom((Number)value);
            }
        }
        ,
        WeftYarnType {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getWeftYarnType();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setWeftYarnType((String)value);
            }
        }
        ,
        WtOfWeftYarn {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getWtOfWeftYarn();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setWtOfWeftYarn((Number)value);
            }
        }
        ,
        WeaveFinishingDate {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getWeaveFinishingDate();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setWeaveFinishingDate((Date)value);
            }
        }
        ,
        TotalWeavableLength {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getTotalWeavableLength();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setTotalWeavableLength((Number)value);
            }
        }
        ,
        SelvedgeEnds {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getSelvedgeEnds();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setSelvedgeEnds((Number)value);
            }
        }
        ,
        GreyPpiWeaving {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getGreyPpiWeaving();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setGreyPpiWeaving((Number)value);
            }
        }
        ,
        GreyWidthWeaving {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getGreyWidthWeaving();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setGreyWidthWeaving((Number)value);
            }
        }
        ,
        ReedSpaceInch {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getReedSpaceInch();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setReedSpaceInch((Number)value);
            }
        }
        ,
        SelvedgeEndsDent {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getSelvedgeEndsDent();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setSelvedgeEndsDent((Number)value);
            }
        }
        ,
        LoomRpm {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getLoomRpm();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setLoomRpm((Number)value);
            }
        }
        ,
        LoomStartDate {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getLoomStartDate();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setLoomStartDate((Date)value);
            }
        }
        ,
        TotalProdPerDay {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getTotalProdPerDay();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setTotalProdPerDay((Number)value);
            }
        }
        ,
        LoomProdPerDay {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getLoomProdPerDay();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setLoomProdPerDay((Number)value);
            }
        }
        ,
        WeftYarnBrand {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getWeftYarnBrand();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setWeftYarnBrand((String)value);
            }
        }
        ,
        WeftYarnBlend {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getWeftYarnBlend();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setWeftYarnBlend((String)value);
            }
        }
        ,
        TotalWeftReq {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getTotalWeftReq();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setTotalWeftReq((Number)value);
            }
        }
        ,
        DayReqToFinish {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getDayReqToFinish();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setDayReqToFinish((Number)value);
            }
        }
        ,
        GreyEpiTable {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getGreyEpiTable();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setGreyEpiTable((Number)value);
            }
        }
        ,
        GreyWidthFolding {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getGreyWidthFolding();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setGreyWidthFolding((Number)value);
            }
        }
        ,
        GreyWidthTable {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getGreyWidthTable();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setGreyWidthTable((String)value);
            }
        }
        ,
        GreyGsm {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getGreyGsm();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setGreyGsm((Number)value);
            }
        }
        ,
        ReqFoldingProdDay {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getReqFoldingProdDay();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setReqFoldingProdDay((Number)value);
            }
        }
        ,
        GreyPpiTable {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getGreyPpiTable();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setGreyPpiTable((Number)value);
            }
        }
        ,
        GreyFabWt {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getGreyFabWt();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setGreyFabWt((Number)value);
            }
        }
        ,
        InspectionFinishedDate {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getInspectionFinishedDate();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setInspectionFinishedDate((Date)value);
            }
        }
        ,
        TotalYarnReq {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getTotalYarnReq();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setTotalYarnReq((Number)value);
            }
        }
        ,
        TotalYarnAllocated {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getTotalYarnAllocated();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setTotalYarnAllocated((Number)value);
            }
        }
        ,
        RemainingYarnReq {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getRemainingYarnReq();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setRemainingYarnReq((Number)value);
            }
        }
        ,
        TotalYarnAvailable {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getTotalYarnAvailable();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setTotalYarnAvailable((Number)value);
            }
        }
        ,
        YarnPurchaseReq {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getYarnPurchaseReq();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setYarnPurchaseReq((Number)value);
            }
        }
        ,
        PileYarnCount {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getPileYarnCount();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setPileYarnCount((String)value);
            }
        }
        ,
        PileYarnBrand {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getPileYarnBrand();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setPileYarnBrand((String)value);
            }
        }
        ,
        PileYarnEndsInch {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getPileYarnEndsInch();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setPileYarnEndsInch((Number)value);
            }
        }
        ,
        TotalPileYarnEnds {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getTotalPileYarnEnds();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setTotalPileYarnEnds((Number)value);
            }
        }
        ,
        Splits {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getSplits();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setSplits((Number)value);
            }
        }
        ,
        SizeTerry {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getSizeTerry();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setSizeTerry((Number)value);
            }
        }
        ,
        Design {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getDesign();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setDesign((String)value);
            }
        }
        ,
        WeightPileYarn {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getWeightPileYarn();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setWeightPileYarn((Number)value);
            }
        }
        ,
        TotalPileYarnReq {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getTotalPileYarnReq();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setTotalPileYarnReq((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getAttribute11();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getAttribute12();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getAttribute13();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getAttribute14();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getAttribute15();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        FebricProcess {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getFebricProcess();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setFebricProcess((String)value);
            }
        }
        ,
        Weave {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getWeave();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setWeave((String)value);
            }
        }
        ,
        CWPer {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getCWPer();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setCWPer((Number)value);
            }
        }
        ,
        LoomEfficiency {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getLoomEfficiency();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setLoomEfficiency((Number)value);
            }
        }
        ,
        WarpYarnCount {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getWarpYarnCount();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setWarpYarnCount((String)value);
            }
        }
        ,
        WeftCount {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getWeftCount();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setWeftCount((String)value);
            }
        }
        ,
        PwcOdmBreakDownWarpCountEO {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getPwcOdmBreakDownWarpCountEO();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PwcOdmBreakDownWeftCountEO {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getPwcOdmBreakDownWeftCountEO();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PwcOdmBreakDownPileCountEO {
            public Object get(PwcOdmBreakDownHdrEOImpl obj) {
                return obj.getPwcOdmBreakDownPileCountEO();
            }

            public void put(PwcOdmBreakDownHdrEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(PwcOdmBreakDownHdrEOImpl object);

        public abstract void put(PwcOdmBreakDownHdrEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int GDNUMBER = AttributesEnum.GdNumber.index();
    public static final int SALEORDERNUMBER = AttributesEnum.SaleOrderNumber.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int CONSTRACTION1 = AttributesEnum.Constraction1.index();
    public static final int CONTRACTION2 = AttributesEnum.Contraction2.index();
    public static final int CONTRACTION3 = AttributesEnum.Contraction3.index();
    public static final int CONTRACTION4 = AttributesEnum.Contraction4.index();
    public static final int GREIGEWIDTH = AttributesEnum.GreigeWidth.index();
    public static final int FINISHWIDTH = AttributesEnum.FinishWidth.index();
    public static final int ORDERQTYYDS = AttributesEnum.OrderQtyYds.index();
    public static final int ORDERQTYMTR = AttributesEnum.OrderQtyMtr.index();
    public static final int LASTDELIVERYDATE = AttributesEnum.LastDeliveryDate.index();
    public static final int BLEND = AttributesEnum.Blend.index();
    public static final int PROCESSLOSS = AttributesEnum.ProcessLoss.index();
    public static final int BEAMWIDTH = AttributesEnum.BeamWidth.index();
    public static final int LOOMTYPE = AttributesEnum.LoomType.index();
    public static final int BEAMDIAMM = AttributesEnum.BeamDiaMm.index();
    public static final int REQSIZELENGTH = AttributesEnum.ReqSizeLength.index();
    public static final int NUMBERBEAM = AttributesEnum.NumberBeam.index();
    public static final int WTOFWARP = AttributesEnum.WtOfWarp.index();
    public static final int TOTALENDS = AttributesEnum.TotalEnds.index();
    public static final int WARPINGSTARTDATE = AttributesEnum.WarpingStartDate.index();
    public static final int YARNBRAND = AttributesEnum.YarnBrand.index();
    public static final int YARNLOT = AttributesEnum.YarnLot.index();
    public static final int YARNTYPE = AttributesEnum.YarnType.index();
    public static final int YARNBLEND = AttributesEnum.YarnBlend.index();
    public static final int BEAMLENGTH = AttributesEnum.BeamLength.index();
    public static final int TOTALWARPREQ = AttributesEnum.TotalWarpReq.index();
    public static final int WARPINGFINISHINGDATE = AttributesEnum.WarpingFinishingDate.index();
    public static final int DROPPERTHICKNESSMM = AttributesEnum.DropperThicknessMm.index();
    public static final int GREYEPIWEAVING = AttributesEnum.GreyEpiWeaving.index();
    public static final int REEDCOUNT = AttributesEnum.ReedCount.index();
    public static final int ENDDENT = AttributesEnum.EndDent.index();
    public static final int SELVEDGEENDSBOTHSIDES = AttributesEnum.SelvedgeEndsBothSides.index();
    public static final int SELVEDGESIZE = AttributesEnum.SelvedgeSize.index();
    public static final int PLANLOOM = AttributesEnum.PlanLoom.index();
    public static final int WEFTYARNTYPE = AttributesEnum.WeftYarnType.index();
    public static final int WTOFWEFTYARN = AttributesEnum.WtOfWeftYarn.index();
    public static final int WEAVEFINISHINGDATE = AttributesEnum.WeaveFinishingDate.index();
    public static final int TOTALWEAVABLELENGTH = AttributesEnum.TotalWeavableLength.index();
    public static final int SELVEDGEENDS = AttributesEnum.SelvedgeEnds.index();
    public static final int GREYPPIWEAVING = AttributesEnum.GreyPpiWeaving.index();
    public static final int GREYWIDTHWEAVING = AttributesEnum.GreyWidthWeaving.index();
    public static final int REEDSPACEINCH = AttributesEnum.ReedSpaceInch.index();
    public static final int SELVEDGEENDSDENT = AttributesEnum.SelvedgeEndsDent.index();
    public static final int LOOMRPM = AttributesEnum.LoomRpm.index();
    public static final int LOOMSTARTDATE = AttributesEnum.LoomStartDate.index();
    public static final int TOTALPRODPERDAY = AttributesEnum.TotalProdPerDay.index();
    public static final int LOOMPRODPERDAY = AttributesEnum.LoomProdPerDay.index();
    public static final int WEFTYARNBRAND = AttributesEnum.WeftYarnBrand.index();
    public static final int WEFTYARNBLEND = AttributesEnum.WeftYarnBlend.index();
    public static final int TOTALWEFTREQ = AttributesEnum.TotalWeftReq.index();
    public static final int DAYREQTOFINISH = AttributesEnum.DayReqToFinish.index();
    public static final int GREYEPITABLE = AttributesEnum.GreyEpiTable.index();
    public static final int GREYWIDTHFOLDING = AttributesEnum.GreyWidthFolding.index();
    public static final int GREYWIDTHTABLE = AttributesEnum.GreyWidthTable.index();
    public static final int GREYGSM = AttributesEnum.GreyGsm.index();
    public static final int REQFOLDINGPRODDAY = AttributesEnum.ReqFoldingProdDay.index();
    public static final int GREYPPITABLE = AttributesEnum.GreyPpiTable.index();
    public static final int GREYFABWT = AttributesEnum.GreyFabWt.index();
    public static final int INSPECTIONFINISHEDDATE = AttributesEnum.InspectionFinishedDate.index();
    public static final int TOTALYARNREQ = AttributesEnum.TotalYarnReq.index();
    public static final int TOTALYARNALLOCATED = AttributesEnum.TotalYarnAllocated.index();
    public static final int REMAININGYARNREQ = AttributesEnum.RemainingYarnReq.index();
    public static final int TOTALYARNAVAILABLE = AttributesEnum.TotalYarnAvailable.index();
    public static final int YARNPURCHASEREQ = AttributesEnum.YarnPurchaseReq.index();
    public static final int PILEYARNCOUNT = AttributesEnum.PileYarnCount.index();
    public static final int PILEYARNBRAND = AttributesEnum.PileYarnBrand.index();
    public static final int PILEYARNENDSINCH = AttributesEnum.PileYarnEndsInch.index();
    public static final int TOTALPILEYARNENDS = AttributesEnum.TotalPileYarnEnds.index();
    public static final int SPLITS = AttributesEnum.Splits.index();
    public static final int SIZETERRY = AttributesEnum.SizeTerry.index();
    public static final int DESIGN = AttributesEnum.Design.index();
    public static final int WEIGHTPILEYARN = AttributesEnum.WeightPileYarn.index();
    public static final int TOTALPILEYARNREQ = AttributesEnum.TotalPileYarnReq.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int FEBRICPROCESS = AttributesEnum.FebricProcess.index();
    public static final int WEAVE = AttributesEnum.Weave.index();
    public static final int CWPER = AttributesEnum.CWPer.index();
    public static final int LOOMEFFICIENCY = AttributesEnum.LoomEfficiency.index();
    public static final int WARPYARNCOUNT = AttributesEnum.WarpYarnCount.index();
    public static final int WEFTCOUNT = AttributesEnum.WeftCount.index();
    public static final int PWCODMBREAKDOWNWARPCOUNTEO = AttributesEnum.PwcOdmBreakDownWarpCountEO.index();
    public static final int PWCODMBREAKDOWNWEFTCOUNTEO = AttributesEnum.PwcOdmBreakDownWeftCountEO.index();
    public static final int PWCODMBREAKDOWNPILECOUNTEO = AttributesEnum.PwcOdmBreakDownPileCountEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PwcOdmBreakDownHdrEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.BreakDownPaper.EO.PwcOdmBreakDownHdrEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for GdNumber, using the alias name GdNumber.
     * @return the GdNumber
     */
    public String getGdNumber() {
        return (String)getAttributeInternal(GDNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for GdNumber.
     * @param value value to set the GdNumber
     */
    public void setGdNumber(String value) {
        setAttributeInternal(GDNUMBER, value);
    }

    /**
     * Gets the attribute value for SaleOrderNumber, using the alias name SaleOrderNumber.
     * @return the SaleOrderNumber
     */
    public Number getSaleOrderNumber() {
        return (Number)getAttributeInternal(SALEORDERNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for SaleOrderNumber.
     * @param value value to set the SaleOrderNumber
     */
    public void setSaleOrderNumber(Number value) {
        setAttributeInternal(SALEORDERNUMBER, value);
    }

    /**
     * Gets the attribute value for ItemId, using the alias name ItemId.
     * @return the ItemId
     */
    public Number getItemId() {
        return (Number)getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemId.
     * @param value value to set the ItemId
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for Constraction1, using the alias name Constraction1.
     * @return the Constraction1
     */
    public String getConstraction1() {
        return (String)getAttributeInternal(CONSTRACTION1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Constraction1.
     * @param value value to set the Constraction1
     */
    public void setConstraction1(String value) {
        setAttributeInternal(CONSTRACTION1, value);
    }

    /**
     * Gets the attribute value for Contraction2, using the alias name Contraction2.
     * @return the Contraction2
     */
    public String getContraction2() {
        return (String)getAttributeInternal(CONTRACTION2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Contraction2.
     * @param value value to set the Contraction2
     */
    public void setContraction2(String value) {
        setAttributeInternal(CONTRACTION2, value);
    }

    /**
     * Gets the attribute value for Contraction3, using the alias name Contraction3.
     * @return the Contraction3
     */
    public Number getContraction3() {
        return (Number)getAttributeInternal(CONTRACTION3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Contraction3.
     * @param value value to set the Contraction3
     */
    public void setContraction3(Number value) {
        setAttributeInternal(CONTRACTION3, value);
    }

    /**
     * Gets the attribute value for Contraction4, using the alias name Contraction4.
     * @return the Contraction4
     */
    public Number getContraction4() {
        return (Number)getAttributeInternal(CONTRACTION4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Contraction4.
     * @param value value to set the Contraction4
     */
    public void setContraction4(Number value) {
        setAttributeInternal(CONTRACTION4, value);
    }

    /**
     * Gets the attribute value for GreigeWidth, using the alias name GreigeWidth.
     * @return the GreigeWidth
     */
    public Number getGreigeWidth() {
        return (Number)getAttributeInternal(GREIGEWIDTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for GreigeWidth.
     * @param value value to set the GreigeWidth
     */
    public void setGreigeWidth(Number value) {
        setAttributeInternal(GREIGEWIDTH, value);
    }

    /**
     * Gets the attribute value for FinishWidth, using the alias name FinishWidth.
     * @return the FinishWidth
     */
    public Number getFinishWidth() {
        return (Number)getAttributeInternal(FINISHWIDTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for FinishWidth.
     * @param value value to set the FinishWidth
     */
    public void setFinishWidth(Number value) {
        setAttributeInternal(FINISHWIDTH, value);
    }


    /**
     * Gets the attribute value for OrderQtyYds, using the alias name OrderQtyYds.
     * @return the OrderQtyYds
     */
    public Number getOrderQtyYds() {
        return (Number)getAttributeInternal(ORDERQTYYDS);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderQtyYds.
     * @param value value to set the OrderQtyYds
     */
    public void setOrderQtyYds(Number value) {
        setAttributeInternal(ORDERQTYYDS, value);
    }

    /**
     * Gets the attribute value for OrderQtyMtr, using the alias name OrderQtyMtr.
     * @return the OrderQtyMtr
     */
    public Number getOrderQtyMtr() {
        return (Number)getAttributeInternal(ORDERQTYMTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderQtyMtr.
     * @param value value to set the OrderQtyMtr
     */
    public void setOrderQtyMtr(Number value) {
        setAttributeInternal(ORDERQTYMTR, value);
    }

    /**
     * Gets the attribute value for LastDeliveryDate, using the alias name LastDeliveryDate.
     * @return the LastDeliveryDate
     */
    public Date getLastDeliveryDate() {
        return (Date)getAttributeInternal(LASTDELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastDeliveryDate.
     * @param value value to set the LastDeliveryDate
     */
    public void setLastDeliveryDate(Date value) {
        setAttributeInternal(LASTDELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for Blend, using the alias name Blend.
     * @return the Blend
     */
    public String getBlend() {
        return (String)getAttributeInternal(BLEND);
    }

    /**
     * Sets <code>value</code> as the attribute value for Blend.
     * @param value value to set the Blend
     */
    public void setBlend(String value) {
        setAttributeInternal(BLEND, value);
    }

    /**
     * Gets the attribute value for ProcessLoss, using the alias name ProcessLoss.
     * @return the ProcessLoss
     */
    public Number getProcessLoss() {
        return (Number)getAttributeInternal(PROCESSLOSS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProcessLoss.
     * @param value value to set the ProcessLoss
     */
    public void setProcessLoss(Number value) {
        setAttributeInternal(PROCESSLOSS, value);
    }

    /**
     * Gets the attribute value for BeamWidth, using the alias name BeamWidth.
     * @return the BeamWidth
     */
    public String getBeamWidth() {
        return (String)getAttributeInternal(BEAMWIDTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for BeamWidth.
     * @param value value to set the BeamWidth
     */
    public void setBeamWidth(String value) {
        setAttributeInternal(BEAMWIDTH, value);
    }

    /**
     * Gets the attribute value for LoomType, using the alias name LoomType.
     * @return the LoomType
     */
    public String getLoomType() {
        return (String)getAttributeInternal(LOOMTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LoomType.
     * @param value value to set the LoomType
     */
    public void setLoomType(String value) {
        setAttributeInternal(LOOMTYPE, value);
    }

    /**
     * Gets the attribute value for BeamDiaMm, using the alias name BeamDiaMm.
     * @return the BeamDiaMm
     */
    public Number getBeamDiaMm() {
        return (Number)getAttributeInternal(BEAMDIAMM);
    }

    /**
     * Sets <code>value</code> as the attribute value for BeamDiaMm.
     * @param value value to set the BeamDiaMm
     */
    public void setBeamDiaMm(Number value) {
        setAttributeInternal(BEAMDIAMM, value);
    }

    /**
     * Gets the attribute value for ReqSizeLength, using the alias name ReqSizeLength.
     * @return the ReqSizeLength
     */
    public Number getReqSizeLength() {
        return (Number)getAttributeInternal(REQSIZELENGTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReqSizeLength.
     * @param value value to set the ReqSizeLength
     */
    public void setReqSizeLength(Number value) {
        setAttributeInternal(REQSIZELENGTH, value);
    }

    /**
     * Gets the attribute value for NumberBeam, using the alias name NumberBeam.
     * @return the NumberBeam
     */
    public Number getNumberBeam() {
        return (Number)getAttributeInternal(NUMBERBEAM);
    }

    /**
     * Sets <code>value</code> as the attribute value for NumberBeam.
     * @param value value to set the NumberBeam
     */
    public void setNumberBeam(Number value) {
        setAttributeInternal(NUMBERBEAM, value);
    }

    /**
     * Gets the attribute value for WtOfWarp, using the alias name WtOfWarp.
     * @return the WtOfWarp
     */
    public Number getWtOfWarp() {
        return (Number)getAttributeInternal(WTOFWARP);
    }

    /**
     * Sets <code>value</code> as the attribute value for WtOfWarp.
     * @param value value to set the WtOfWarp
     */
    public void setWtOfWarp(Number value) {
        setAttributeInternal(WTOFWARP, value);
    }

    /**
     * Gets the attribute value for TotalEnds, using the alias name TotalEnds.
     * @return the TotalEnds
     */
    public Number getTotalEnds() {
        return (Number)getAttributeInternal(TOTALENDS);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalEnds.
     * @param value value to set the TotalEnds
     */
    public void setTotalEnds(Number value) {
        setAttributeInternal(TOTALENDS, value);
    }

    /**
     * Gets the attribute value for WarpingStartDate, using the alias name WarpingStartDate.
     * @return the WarpingStartDate
     */
    public Date getWarpingStartDate() {
        return (Date)getAttributeInternal(WARPINGSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WarpingStartDate.
     * @param value value to set the WarpingStartDate
     */
    public void setWarpingStartDate(Date value) {
        setAttributeInternal(WARPINGSTARTDATE, value);
    }


    /**
     * Gets the attribute value for YarnBrand, using the alias name YarnBrand.
     * @return the YarnBrand
     */
    public String getYarnBrand() {
        return (String)getAttributeInternal(YARNBRAND);
    }

    /**
     * Sets <code>value</code> as the attribute value for YarnBrand.
     * @param value value to set the YarnBrand
     */
    public void setYarnBrand(String value) {
        setAttributeInternal(YARNBRAND, value);
    }

    /**
     * Gets the attribute value for YarnLot, using the alias name YarnLot.
     * @return the YarnLot
     */
    public String getYarnLot() {
        return (String)getAttributeInternal(YARNLOT);
    }

    /**
     * Sets <code>value</code> as the attribute value for YarnLot.
     * @param value value to set the YarnLot
     */
    public void setYarnLot(String value) {
        setAttributeInternal(YARNLOT, value);
    }

    /**
     * Gets the attribute value for YarnType, using the alias name YarnType.
     * @return the YarnType
     */
    public String getYarnType() {
        return (String)getAttributeInternal(YARNTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for YarnType.
     * @param value value to set the YarnType
     */
    public void setYarnType(String value) {
        setAttributeInternal(YARNTYPE, value);
    }

    /**
     * Gets the attribute value for YarnBlend, using the alias name YarnBlend.
     * @return the YarnBlend
     */
    public String getYarnBlend() {
        return (String)getAttributeInternal(YARNBLEND);
    }

    /**
     * Sets <code>value</code> as the attribute value for YarnBlend.
     * @param value value to set the YarnBlend
     */
    public void setYarnBlend(String value) {
        setAttributeInternal(YARNBLEND, value);
    }

    /**
     * Gets the attribute value for BeamLength, using the alias name BeamLength.
     * @return the BeamLength
     */
    public String getBeamLength() {
        return (String)getAttributeInternal(BEAMLENGTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for BeamLength.
     * @param value value to set the BeamLength
     */
    public void setBeamLength(String value) {
        setAttributeInternal(BEAMLENGTH, value);
    }

    /**
     * Gets the attribute value for TotalWarpReq, using the alias name TotalWarpReq.
     * @return the TotalWarpReq
     */
    public Number getTotalWarpReq() {
        return (Number)getAttributeInternal(TOTALWARPREQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalWarpReq.
     * @param value value to set the TotalWarpReq
     */
    public void setTotalWarpReq(Number value) {
        setAttributeInternal(TOTALWARPREQ, value);
    }

    /**
     * Gets the attribute value for WarpingFinishingDate, using the alias name WarpingFinishingDate.
     * @return the WarpingFinishingDate
     */
    public Date getWarpingFinishingDate() {
        return (Date)getAttributeInternal(WARPINGFINISHINGDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WarpingFinishingDate.
     * @param value value to set the WarpingFinishingDate
     */
    public void setWarpingFinishingDate(Date value) {
        setAttributeInternal(WARPINGFINISHINGDATE, value);
    }

    /**
     * Gets the attribute value for DropperThicknessMm, using the alias name DropperThicknessMm.
     * @return the DropperThicknessMm
     */
    public Number getDropperThicknessMm() {
        return (Number)getAttributeInternal(DROPPERTHICKNESSMM);
    }

    /**
     * Sets <code>value</code> as the attribute value for DropperThicknessMm.
     * @param value value to set the DropperThicknessMm
     */
    public void setDropperThicknessMm(Number value) {
        setAttributeInternal(DROPPERTHICKNESSMM, value);
    }

    /**
     * Gets the attribute value for GreyEpiWeaving, using the alias name GreyEpiWeaving.
     * @return the GreyEpiWeaving
     */
    public Number getGreyEpiWeaving() {
        return (Number)getAttributeInternal(GREYEPIWEAVING);
    }

    /**
     * Sets <code>value</code> as the attribute value for GreyEpiWeaving.
     * @param value value to set the GreyEpiWeaving
     */
    public void setGreyEpiWeaving(Number value) {
        setAttributeInternal(GREYEPIWEAVING, value);
    }

    /**
     * Gets the attribute value for ReedCount, using the alias name ReedCount.
     * @return the ReedCount
     */
    public Number getReedCount() {
        return (Number)getAttributeInternal(REEDCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReedCount.
     * @param value value to set the ReedCount
     */
    public void setReedCount(Number value) {
        setAttributeInternal(REEDCOUNT, value);
    }

    /**
     * Gets the attribute value for EndDent, using the alias name EndDent.
     * @return the EndDent
     */
    public Number getEndDent() {
        return (Number)getAttributeInternal(ENDDENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndDent.
     * @param value value to set the EndDent
     */
    public void setEndDent(Number value) {
        setAttributeInternal(ENDDENT, value);
    }

    /**
     * Gets the attribute value for SelvedgeEndsBothSides, using the alias name SelvedgeEndsBothSides.
     * @return the SelvedgeEndsBothSides
     */
    public Number getSelvedgeEndsBothSides() {
        return (Number)getAttributeInternal(SELVEDGEENDSBOTHSIDES);
    }

    /**
     * Sets <code>value</code> as the attribute value for SelvedgeEndsBothSides.
     * @param value value to set the SelvedgeEndsBothSides
     */
    public void setSelvedgeEndsBothSides(Number value) {
        setAttributeInternal(SELVEDGEENDSBOTHSIDES, value);
    }

    /**
     * Gets the attribute value for SelvedgeSize, using the alias name SelvedgeSize.
     * @return the SelvedgeSize
     */
    public Number getSelvedgeSize() {
        return (Number)getAttributeInternal(SELVEDGESIZE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SelvedgeSize.
     * @param value value to set the SelvedgeSize
     */
    public void setSelvedgeSize(Number value) {
        setAttributeInternal(SELVEDGESIZE, value);
    }

    /**
     * Gets the attribute value for PlanLoom, using the alias name PlanLoom.
     * @return the PlanLoom
     */
    public Number getPlanLoom() {
        return (Number)getAttributeInternal(PLANLOOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlanLoom.
     * @param value value to set the PlanLoom
     */
    public void setPlanLoom(Number value) {
        setAttributeInternal(PLANLOOM, value);
    }


    /**
     * Gets the attribute value for WeftYarnType, using the alias name WeftYarnType.
     * @return the WeftYarnType
     */
    public String getWeftYarnType() {
        return (String)getAttributeInternal(WEFTYARNTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WeftYarnType.
     * @param value value to set the WeftYarnType
     */
    public void setWeftYarnType(String value) {
        setAttributeInternal(WEFTYARNTYPE, value);
    }

    /**
     * Gets the attribute value for WtOfWeftYarn, using the alias name WtOfWeftYarn.
     * @return the WtOfWeftYarn
     */
    public Number getWtOfWeftYarn() {
        return (Number)getAttributeInternal(WTOFWEFTYARN);
    }

    /**
     * Sets <code>value</code> as the attribute value for WtOfWeftYarn.
     * @param value value to set the WtOfWeftYarn
     */
    public void setWtOfWeftYarn(Number value) {
        setAttributeInternal(WTOFWEFTYARN, value);
    }

    /**
     * Gets the attribute value for WeaveFinishingDate, using the alias name WeaveFinishingDate.
     * @return the WeaveFinishingDate
     */
    public Date getWeaveFinishingDate() {
        return (Date)getAttributeInternal(WEAVEFINISHINGDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WeaveFinishingDate.
     * @param value value to set the WeaveFinishingDate
     */
    public void setWeaveFinishingDate(Date value) {
        setAttributeInternal(WEAVEFINISHINGDATE, value);
    }

    /**
     * Gets the attribute value for TotalWeavableLength, using the alias name TotalWeavableLength.
     * @return the TotalWeavableLength
     */
    public Number getTotalWeavableLength() {
        return (Number)getAttributeInternal(TOTALWEAVABLELENGTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalWeavableLength.
     * @param value value to set the TotalWeavableLength
     */
    public void setTotalWeavableLength(Number value) {
        setAttributeInternal(TOTALWEAVABLELENGTH, value);
    }

    /**
     * Gets the attribute value for SelvedgeEnds, using the alias name SelvedgeEnds.
     * @return the SelvedgeEnds
     */
    public Number getSelvedgeEnds() {
        return (Number)getAttributeInternal(SELVEDGEENDS);
    }

    /**
     * Sets <code>value</code> as the attribute value for SelvedgeEnds.
     * @param value value to set the SelvedgeEnds
     */
    public void setSelvedgeEnds(Number value) {
        setAttributeInternal(SELVEDGEENDS, value);
    }

    /**
     * Gets the attribute value for GreyPpiWeaving, using the alias name GreyPpiWeaving.
     * @return the GreyPpiWeaving
     */
    public Number getGreyPpiWeaving() {
        return (Number)getAttributeInternal(GREYPPIWEAVING);
    }

    /**
     * Sets <code>value</code> as the attribute value for GreyPpiWeaving.
     * @param value value to set the GreyPpiWeaving
     */
    public void setGreyPpiWeaving(Number value) {
        setAttributeInternal(GREYPPIWEAVING, value);
    }

    /**
     * Gets the attribute value for GreyWidthWeaving, using the alias name GreyWidthWeaving.
     * @return the GreyWidthWeaving
     */
    public Number getGreyWidthWeaving() {
        return (Number)getAttributeInternal(GREYWIDTHWEAVING);
    }

    /**
     * Sets <code>value</code> as the attribute value for GreyWidthWeaving.
     * @param value value to set the GreyWidthWeaving
     */
    public void setGreyWidthWeaving(Number value) {
        setAttributeInternal(GREYWIDTHWEAVING, value);
    }

    /**
     * Gets the attribute value for ReedSpaceInch, using the alias name ReedSpaceInch.
     * @return the ReedSpaceInch
     */
    public Number getReedSpaceInch() {
        return (Number)getAttributeInternal(REEDSPACEINCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReedSpaceInch.
     * @param value value to set the ReedSpaceInch
     */
    public void setReedSpaceInch(Number value) {
        setAttributeInternal(REEDSPACEINCH, value);
    }

    /**
     * Gets the attribute value for SelvedgeEndsDent, using the alias name SelvedgeEndsDent.
     * @return the SelvedgeEndsDent
     */
    public Number getSelvedgeEndsDent() {
        return (Number)getAttributeInternal(SELVEDGEENDSDENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for SelvedgeEndsDent.
     * @param value value to set the SelvedgeEndsDent
     */
    public void setSelvedgeEndsDent(Number value) {
        setAttributeInternal(SELVEDGEENDSDENT, value);
    }

    /**
     * Gets the attribute value for LoomRpm, using the alias name LoomRpm.
     * @return the LoomRpm
     */
    public Number getLoomRpm() {
        return (Number)getAttributeInternal(LOOMRPM);
    }

    /**
     * Sets <code>value</code> as the attribute value for LoomRpm.
     * @param value value to set the LoomRpm
     */
    public void setLoomRpm(Number value) {
        setAttributeInternal(LOOMRPM, value);
    }

    /**
     * Gets the attribute value for LoomStartDate, using the alias name LoomStartDate.
     * @return the LoomStartDate
     */
    public Date getLoomStartDate() {
        return (Date)getAttributeInternal(LOOMSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LoomStartDate.
     * @param value value to set the LoomStartDate
     */
    public void setLoomStartDate(Date value) {
        setAttributeInternal(LOOMSTARTDATE, value);
    }

    /**
     * Gets the attribute value for TotalProdPerDay, using the alias name TotalProdPerDay.
     * @return the TotalProdPerDay
     */
    public Number getTotalProdPerDay() {
        return (Number)getAttributeInternal(TOTALPRODPERDAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalProdPerDay.
     * @param value value to set the TotalProdPerDay
     */
    public void setTotalProdPerDay(Number value) {
        setAttributeInternal(TOTALPRODPERDAY, value);
    }

    /**
     * Gets the attribute value for LoomProdPerDay, using the alias name LoomProdPerDay.
     * @return the LoomProdPerDay
     */
    public Number getLoomProdPerDay() {
        return (Number)getAttributeInternal(LOOMPRODPERDAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LoomProdPerDay.
     * @param value value to set the LoomProdPerDay
     */
    public void setLoomProdPerDay(Number value) {
        setAttributeInternal(LOOMPRODPERDAY, value);
    }

    /**
     * Gets the attribute value for WeftYarnBrand, using the alias name WeftYarnBrand.
     * @return the WeftYarnBrand
     */
    public String getWeftYarnBrand() {
        return (String)getAttributeInternal(WEFTYARNBRAND);
    }

    /**
     * Sets <code>value</code> as the attribute value for WeftYarnBrand.
     * @param value value to set the WeftYarnBrand
     */
    public void setWeftYarnBrand(String value) {
        setAttributeInternal(WEFTYARNBRAND, value);
    }

    /**
     * Gets the attribute value for WeftYarnBlend, using the alias name WeftYarnBlend.
     * @return the WeftYarnBlend
     */
    public String getWeftYarnBlend() {
        return (String)getAttributeInternal(WEFTYARNBLEND);
    }

    /**
     * Sets <code>value</code> as the attribute value for WeftYarnBlend.
     * @param value value to set the WeftYarnBlend
     */
    public void setWeftYarnBlend(String value) {
        setAttributeInternal(WEFTYARNBLEND, value);
    }

    /**
     * Gets the attribute value for TotalWeftReq, using the alias name TotalWeftReq.
     * @return the TotalWeftReq
     */
    public Number getTotalWeftReq() {
        return (Number)getAttributeInternal(TOTALWEFTREQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalWeftReq.
     * @param value value to set the TotalWeftReq
     */
    public void setTotalWeftReq(Number value) {
        setAttributeInternal(TOTALWEFTREQ, value);
    }

    /**
     * Gets the attribute value for DayReqToFinish, using the alias name DayReqToFinish.
     * @return the DayReqToFinish
     */
    public Number getDayReqToFinish() {
        return (Number)getAttributeInternal(DAYREQTOFINISH);
    }

    /**
     * Sets <code>value</code> as the attribute value for DayReqToFinish.
     * @param value value to set the DayReqToFinish
     */
    public void setDayReqToFinish(Number value) {
        setAttributeInternal(DAYREQTOFINISH, value);
    }

    /**
     * Gets the attribute value for GreyEpiTable, using the alias name GreyEpiTable.
     * @return the GreyEpiTable
     */
    public Number getGreyEpiTable() {
        return (Number)getAttributeInternal(GREYEPITABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GreyEpiTable.
     * @param value value to set the GreyEpiTable
     */
    public void setGreyEpiTable(Number value) {
        setAttributeInternal(GREYEPITABLE, value);
    }

    /**
     * Gets the attribute value for GreyWidthFolding, using the alias name GreyWidthFolding.
     * @return the GreyWidthFolding
     */
    public Number getGreyWidthFolding() {
        return (Number)getAttributeInternal(GREYWIDTHFOLDING);
    }

    /**
     * Sets <code>value</code> as the attribute value for GreyWidthFolding.
     * @param value value to set the GreyWidthFolding
     */
    public void setGreyWidthFolding(Number value) {
        setAttributeInternal(GREYWIDTHFOLDING, value);
    }

    /**
     * Gets the attribute value for GreyWidthTable, using the alias name GreyWidthTable.
     * @return the GreyWidthTable
     */
    public String getGreyWidthTable() {
        return (String)getAttributeInternal(GREYWIDTHTABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GreyWidthTable.
     * @param value value to set the GreyWidthTable
     */
    public void setGreyWidthTable(String value) {
        setAttributeInternal(GREYWIDTHTABLE, value);
    }

    /**
     * Gets the attribute value for GreyGsm, using the alias name GreyGsm.
     * @return the GreyGsm
     */
    public Number getGreyGsm() {
        return (Number)getAttributeInternal(GREYGSM);
    }

    /**
     * Sets <code>value</code> as the attribute value for GreyGsm.
     * @param value value to set the GreyGsm
     */
    public void setGreyGsm(Number value) {
        setAttributeInternal(GREYGSM, value);
    }

    /**
     * Gets the attribute value for ReqFoldingProdDay, using the alias name ReqFoldingProdDay.
     * @return the ReqFoldingProdDay
     */
    public Number getReqFoldingProdDay() {
        return (Number)getAttributeInternal(REQFOLDINGPRODDAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReqFoldingProdDay.
     * @param value value to set the ReqFoldingProdDay
     */
    public void setReqFoldingProdDay(Number value) {
        setAttributeInternal(REQFOLDINGPRODDAY, value);
    }

    /**
     * Gets the attribute value for GreyPpiTable, using the alias name GreyPpiTable.
     * @return the GreyPpiTable
     */
    public Number getGreyPpiTable() {
        return (Number)getAttributeInternal(GREYPPITABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GreyPpiTable.
     * @param value value to set the GreyPpiTable
     */
    public void setGreyPpiTable(Number value) {
        setAttributeInternal(GREYPPITABLE, value);
    }

    /**
     * Gets the attribute value for GreyFabWt, using the alias name GreyFabWt.
     * @return the GreyFabWt
     */
    public Number getGreyFabWt() {
        return (Number)getAttributeInternal(GREYFABWT);
    }

    /**
     * Sets <code>value</code> as the attribute value for GreyFabWt.
     * @param value value to set the GreyFabWt
     */
    public void setGreyFabWt(Number value) {
        setAttributeInternal(GREYFABWT, value);
    }

    /**
     * Gets the attribute value for InspectionFinishedDate, using the alias name InspectionFinishedDate.
     * @return the InspectionFinishedDate
     */
    public Date getInspectionFinishedDate() {
        return (Date)getAttributeInternal(INSPECTIONFINISHEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InspectionFinishedDate.
     * @param value value to set the InspectionFinishedDate
     */
    public void setInspectionFinishedDate(Date value) {
        setAttributeInternal(INSPECTIONFINISHEDDATE, value);
    }

    /**
     * Gets the attribute value for TotalYarnReq, using the alias name TotalYarnReq.
     * @return the TotalYarnReq
     */
    public Number getTotalYarnReq() {
        return (Number)getAttributeInternal(TOTALYARNREQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalYarnReq.
     * @param value value to set the TotalYarnReq
     */
    public void setTotalYarnReq(Number value) {
        setAttributeInternal(TOTALYARNREQ, value);
    }

    /**
     * Gets the attribute value for TotalYarnAllocated, using the alias name TotalYarnAllocated.
     * @return the TotalYarnAllocated
     */
    public Number getTotalYarnAllocated() {
        return (Number)getAttributeInternal(TOTALYARNALLOCATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalYarnAllocated.
     * @param value value to set the TotalYarnAllocated
     */
    public void setTotalYarnAllocated(Number value) {
        setAttributeInternal(TOTALYARNALLOCATED, value);
    }

    /**
     * Gets the attribute value for RemainingYarnReq, using the alias name RemainingYarnReq.
     * @return the RemainingYarnReq
     */
    public Number getRemainingYarnReq() {
        return (Number)getAttributeInternal(REMAININGYARNREQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for RemainingYarnReq.
     * @param value value to set the RemainingYarnReq
     */
    public void setRemainingYarnReq(Number value) {
        setAttributeInternal(REMAININGYARNREQ, value);
    }

    /**
     * Gets the attribute value for TotalYarnAvailable, using the alias name TotalYarnAvailable.
     * @return the TotalYarnAvailable
     */
    public Number getTotalYarnAvailable() {
        return (Number)getAttributeInternal(TOTALYARNAVAILABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalYarnAvailable.
     * @param value value to set the TotalYarnAvailable
     */
    public void setTotalYarnAvailable(Number value) {
        setAttributeInternal(TOTALYARNAVAILABLE, value);
    }

    /**
     * Gets the attribute value for YarnPurchaseReq, using the alias name YarnPurchaseReq.
     * @return the YarnPurchaseReq
     */
    public Number getYarnPurchaseReq() {
        return (Number)getAttributeInternal(YARNPURCHASEREQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for YarnPurchaseReq.
     * @param value value to set the YarnPurchaseReq
     */
    public void setYarnPurchaseReq(Number value) {
        setAttributeInternal(YARNPURCHASEREQ, value);
    }

    /**
     * Gets the attribute value for PileYarnCount, using the alias name PileYarnCount.
     * @return the PileYarnCount
     */
    public String getPileYarnCount() {
        return (String)getAttributeInternal(PILEYARNCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for PileYarnCount.
     * @param value value to set the PileYarnCount
     */
    public void setPileYarnCount(String value) {
        setAttributeInternal(PILEYARNCOUNT, value);
    }

    /**
     * Gets the attribute value for PileYarnBrand, using the alias name PileYarnBrand.
     * @return the PileYarnBrand
     */
    public String getPileYarnBrand() {
        return (String)getAttributeInternal(PILEYARNBRAND);
    }

    /**
     * Sets <code>value</code> as the attribute value for PileYarnBrand.
     * @param value value to set the PileYarnBrand
     */
    public void setPileYarnBrand(String value) {
        setAttributeInternal(PILEYARNBRAND, value);
    }

    /**
     * Gets the attribute value for PileYarnEndsInch, using the alias name PileYarnEndsInch.
     * @return the PileYarnEndsInch
     */
    public Number getPileYarnEndsInch() {
        return (Number)getAttributeInternal(PILEYARNENDSINCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for PileYarnEndsInch.
     * @param value value to set the PileYarnEndsInch
     */
    public void setPileYarnEndsInch(Number value) {
        setAttributeInternal(PILEYARNENDSINCH, value);
    }

    /**
     * Gets the attribute value for TotalPileYarnEnds, using the alias name TotalPileYarnEnds.
     * @return the TotalPileYarnEnds
     */
    public Number getTotalPileYarnEnds() {
        return (Number)getAttributeInternal(TOTALPILEYARNENDS);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalPileYarnEnds.
     * @param value value to set the TotalPileYarnEnds
     */
    public void setTotalPileYarnEnds(Number value) {
        setAttributeInternal(TOTALPILEYARNENDS, value);
    }

    /**
     * Gets the attribute value for Splits, using the alias name Splits.
     * @return the Splits
     */
    public Number getSplits() {
        return (Number)getAttributeInternal(SPLITS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Splits.
     * @param value value to set the Splits
     */
    public void setSplits(Number value) {
        setAttributeInternal(SPLITS, value);
    }

    /**
     * Gets the attribute value for SizeTerry, using the alias name SizeTerry.
     * @return the SizeTerry
     */
    public Number getSizeTerry() {
        return (Number)getAttributeInternal(SIZETERRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeTerry.
     * @param value value to set the SizeTerry
     */
    public void setSizeTerry(Number value) {
        setAttributeInternal(SIZETERRY, value);
    }

    /**
     * Gets the attribute value for Design, using the alias name Design.
     * @return the Design
     */
    public String getDesign() {
        return (String)getAttributeInternal(DESIGN);
    }

    /**
     * Sets <code>value</code> as the attribute value for Design.
     * @param value value to set the Design
     */
    public void setDesign(String value) {
        setAttributeInternal(DESIGN, value);
    }

    /**
     * Gets the attribute value for WeightPileYarn, using the alias name WeightPileYarn.
     * @return the WeightPileYarn
     */
    public Number getWeightPileYarn() {
        return (Number)getAttributeInternal(WEIGHTPILEYARN);
    }

    /**
     * Sets <code>value</code> as the attribute value for WeightPileYarn.
     * @param value value to set the WeightPileYarn
     */
    public void setWeightPileYarn(Number value) {
        setAttributeInternal(WEIGHTPILEYARN, value);
    }

    /**
     * Gets the attribute value for TotalPileYarnReq, using the alias name TotalPileYarnReq.
     * @return the TotalPileYarnReq
     */
    public Number getTotalPileYarnReq() {
        return (Number)getAttributeInternal(TOTALPILEYARNREQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalPileYarnReq.
     * @param value value to set the TotalPileYarnReq
     */
    public void setTotalPileYarnReq(Number value) {
        setAttributeInternal(TOTALPILEYARNREQ, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for FebricProcess, using the alias name FebricProcess.
     * @return the FebricProcess
     */
    public String getFebricProcess() {
        return (String)getAttributeInternal(FEBRICPROCESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for FebricProcess.
     * @param value value to set the FebricProcess
     */
    public void setFebricProcess(String value) {
        setAttributeInternal(FEBRICPROCESS, value);
    }

    /**
     * Gets the attribute value for Weave, using the alias name Weave.
     * @return the Weave
     */
    public String getWeave() {
        return (String)getAttributeInternal(WEAVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Weave.
     * @param value value to set the Weave
     */
    public void setWeave(String value) {
        setAttributeInternal(WEAVE, value);
    }

    /**
     * Gets the attribute value for CWPer, using the alias name CWPer.
     * @return the CWPer
     */
    public Number getCWPer() {
        return (Number)getAttributeInternal(CWPER);
    }

    /**
     * Sets <code>value</code> as the attribute value for CWPer.
     * @param value value to set the CWPer
     */
    public void setCWPer(Number value) {
        setAttributeInternal(CWPER, value);
    }

    /**
     * Gets the attribute value for LoomEfficiency, using the alias name LoomEfficiency.
     * @return the LoomEfficiency
     */
    public Number getLoomEfficiency() {
        return (Number)getAttributeInternal(LOOMEFFICIENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LoomEfficiency.
     * @param value value to set the LoomEfficiency
     */
    public void setLoomEfficiency(Number value) {
        setAttributeInternal(LOOMEFFICIENCY, value);
    }

    /**
     * Gets the attribute value for WarpYarnCount, using the alias name WarpYarnCount.
     * @return the WarpYarnCount
     */
    public String getWarpYarnCount() {
        return (String)getAttributeInternal(WARPYARNCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for WarpYarnCount.
     * @param value value to set the WarpYarnCount
     */
    public void setWarpYarnCount(String value) {
        setAttributeInternal(WARPYARNCOUNT, value);
    }

    /**
     * Gets the attribute value for WeftCount, using the alias name WeftCount.
     * @return the WeftCount
     */
    public String getWeftCount() {
        return (String)getAttributeInternal(WEFTCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for WeftCount.
     * @param value value to set the WeftCount
     */
    public void setWeftCount(String value) {
        setAttributeInternal(WEFTCOUNT, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPwcOdmBreakDownWarpCountEO() {
        return (RowIterator)getAttributeInternal(PWCODMBREAKDOWNWARPCOUNTEO);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPwcOdmBreakDownWeftCountEO() {
        return (RowIterator)getAttributeInternal(PWCODMBREAKDOWNWEFTCOUNTEO);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPwcOdmBreakDownPileCountEO() {
        return (RowIterator)getAttributeInternal(PWCODMBREAKDOWNPILECOUNTEO);
    }


    /**
     * @param headerId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number headerId) {
        return new Key(new Object[]{headerId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
