package model.BreakDownPaper.AM.client;

import model.BreakDownPaper.AM.common.PwcOdmBreakDownPaperAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 03 00:08:17 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcOdmBreakDownPaperAMClient extends ApplicationModuleImpl implements PwcOdmBreakDownPaperAM {
    /**
     * This is the default constructor (do not remove).
     */
    public PwcOdmBreakDownPaperAMClient() {
    }

    public void warpDialogListener() {
        Object _ret =
            this.riInvokeExportedMethod(this,"warpDialogListener",null,null);
        return;
    }

    public void weftDialogListener() {
        Object _ret =
            this.riInvokeExportedMethod(this,"weftDialogListener",null,null);
        return;
    }

    public void pileYarnCountDialogListener() {
        Object _ret =
            this.riInvokeExportedMethod(this,"pileYarnCountDialogListener",null,null);
        return;
    }
}
