package model.GradingWeaving.AM.client;

import model.GradingWeaving.AM.common.PwcOdmGradingWeavingAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 09 04:09:24 EDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcOdmGradingWeavingAMClient extends ApplicationModuleImpl implements PwcOdmGradingWeavingAM {
    /**
     * This is the default constructor (do not remove).
     */
    public PwcOdmGradingWeavingAMClient() {
    }

    public void Exceed_TOTALQTY() {
        Object _ret =
            this.riInvokeExportedMethod(this,"Exceed_TOTALQTY",null,null);
        return;
    }
}
