package model.GradingWeaving.VO;

import model.GradingWeaving.EO.PwcOdmGradingWaveingLinesEOImpl;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 31 15:40:50 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcOdmGradingWaveingLinesVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        LineId {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getLineId();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        MachineNumber {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getMachineNumber();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setMachineNumber((String)value);
            }
        }
        ,
        RollNumber {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getRollNumber();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setRollNumber((String)value);
            }
        }
        ,
        TotalQuantity {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getTotalQuantity();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setTotalQuantity((Number)value);
            }
        }
        ,
        Gradea {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getGradea();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setGradea((Number)value);
            }
        }
        ,
        Gradeb {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getGradeb();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setGradeb((Number)value);
            }
        }
        ,
        Gradec {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getGradec();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setGradec((Number)value);
            }
        }
        ,
        Graded {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getGraded();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setGraded((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getRemarks();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        GdId {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getGdId();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setGdId((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setAttribute1((Integer)value);
            }
        }
        ,
        Attribute10 {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setAttribute2((Integer)value);
            }
        }
        ,
        Attribute3 {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setAttribute3((Integer)value);
            }
        }
        ,
        Attribute4 {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setAttribute4((Integer)value);
            }
        }
        ,
        Attribute5 {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        LastUpdatedLogin {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getLastUpdatedLogin();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setLastUpdatedLogin((Number)value);
            }
        }
        ,
        RetrunFlag {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getRetrunFlag();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setRetrunFlag((String)value);
            }
        }
        ,
        SelectedRow {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getSelectedRow();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setSelectedRow((Boolean)value);
            }
        }
        ,
        RequestStatus {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getRequestStatus();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setRequestStatus((String)value);
            }
        }
        ,
        PwcOdmGradingWeavingHeadersVO {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getPwcOdmGradingWeavingHeadersVO();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PwcOdmGradingWeavingLinesMachineNo1 {
            public Object get(PwcOdmGradingWaveingLinesVORowImpl obj) {
                return obj.getPwcOdmGradingWeavingLinesMachineNo1();
            }

            public void put(PwcOdmGradingWaveingLinesVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PwcOdmGradingWaveingLinesVORowImpl object);

        public abstract void put(PwcOdmGradingWaveingLinesVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int MACHINENUMBER = AttributesEnum.MachineNumber.index();
    public static final int ROLLNUMBER = AttributesEnum.RollNumber.index();
    public static final int TOTALQUANTITY = AttributesEnum.TotalQuantity.index();
    public static final int GRADEA = AttributesEnum.Gradea.index();
    public static final int GRADEB = AttributesEnum.Gradeb.index();
    public static final int GRADEC = AttributesEnum.Gradec.index();
    public static final int GRADED = AttributesEnum.Graded.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int GDID = AttributesEnum.GdId.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int LASTUPDATEDLOGIN = AttributesEnum.LastUpdatedLogin.index();
    public static final int RETRUNFLAG = AttributesEnum.RetrunFlag.index();
    public static final int SELECTEDROW = AttributesEnum.SelectedRow.index();
    public static final int REQUESTSTATUS = AttributesEnum.RequestStatus.index();
    public static final int PWCODMGRADINGWEAVINGHEADERSVO = AttributesEnum.PwcOdmGradingWeavingHeadersVO.index();
    public static final int PWCODMGRADINGWEAVINGLINESMACHINENO1 = AttributesEnum.PwcOdmGradingWeavingLinesMachineNo1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PwcOdmGradingWaveingLinesVORowImpl() {
    }

    /**
     * Gets PwcOdmGradingWaveingLinesEO entity object.
     * @return the PwcOdmGradingWaveingLinesEO
     */
    public PwcOdmGradingWaveingLinesEOImpl getPwcOdmGradingWaveingLinesEO() {
        return (PwcOdmGradingWaveingLinesEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for LINE_ID using the alias name LineId.
     * @return the LINE_ID
     */
    public Number getLineId() {
        return (Number)getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_ID using the alias name LineId.
     * @param value value to set the LINE_ID
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for MACHINE_NUMBER using the alias name MachineNumber.
     * @return the MACHINE_NUMBER
     */
    public String getMachineNumber() {
        return (String) getAttributeInternal(MACHINENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for MACHINE_NUMBER using the alias name MachineNumber.
     * @param value value to set the MACHINE_NUMBER
     */
    public void setMachineNumber(String value) {
        setAttributeInternal(MACHINENUMBER, value);
    }

    /**
     * Gets the attribute value for ROLL_NUMBER using the alias name RollNumber.
     * @return the ROLL_NUMBER
     */
    public String getRollNumber() {
        return (String) getAttributeInternal(ROLLNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for ROLL_NUMBER using the alias name RollNumber.
     * @param value value to set the ROLL_NUMBER
     */
    public void setRollNumber(String value) {
        setAttributeInternal(ROLLNUMBER, value);
    }

    /**
     * Gets the attribute value for TOTAL_QUANTITY using the alias name TotalQuantity.
     * @return the TOTAL_QUANTITY
     */
    public Number getTotalQuantity() {
        return (Number)getAttributeInternal(TOTALQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_QUANTITY using the alias name TotalQuantity.
     * @param value value to set the TOTAL_QUANTITY
     */
    public void setTotalQuantity(Number value) {
        setAttributeInternal(TOTALQUANTITY, value);
    }

    /**
     * Gets the attribute value for GRADEA using the alias name Gradea.
     * @return the GRADEA
     */
    public Number getGradea() {
        return (Number)getAttributeInternal(GRADEA);
    }

    /**
     * Sets <code>value</code> as attribute value for GRADEA using the alias name Gradea.
     * @param value value to set the GRADEA
     */
    public void setGradea(Number value) {
        setAttributeInternal(GRADEA, value);
    }

    /**
     * Gets the attribute value for GRADEB using the alias name Gradeb.
     * @return the GRADEB
     */
    public Number getGradeb() {
        return (Number)getAttributeInternal(GRADEB);
    }

    /**
     * Sets <code>value</code> as attribute value for GRADEB using the alias name Gradeb.
     * @param value value to set the GRADEB
     */
    public void setGradeb(Number value) {
        setAttributeInternal(GRADEB, value);
    }

    /**
     * Gets the attribute value for GRADEC using the alias name Gradec.
     * @return the GRADEC
     */
    public Number getGradec() {
        return (Number)getAttributeInternal(GRADEC);
    }

    /**
     * Sets <code>value</code> as attribute value for GRADEC using the alias name Gradec.
     * @param value value to set the GRADEC
     */
    public void setGradec(Number value) {
        setAttributeInternal(GRADEC, value);
    }

    /**
     * Gets the attribute value for GRADED using the alias name Graded.
     * @return the GRADED
     */
    public Number getGraded() {
        return (Number)getAttributeInternal(GRADED);
    }

    /**
     * Sets <code>value</code> as attribute value for GRADED using the alias name Graded.
     * @param value value to set the GRADED
     */
    public void setGraded(Number value) {
        setAttributeInternal(GRADED, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for GD_ID using the alias name GdId.
     * @return the GD_ID
     */
    public Number getGdId() {
        return (Number)getAttributeInternal(GDID);
    }

    /**
     * Sets <code>value</code> as attribute value for GD_ID using the alias name GdId.
     * @param value value to set the GD_ID
     */
    public void setGdId(Number value) {
        setAttributeInternal(GDID, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public Integer getAttribute1() {
        return (Integer) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(Integer value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public Integer getAttribute2() {
        return (Integer) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(Integer value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public Integer getAttribute3() {
        return (Integer) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(Integer value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public Integer getAttribute4() {
        return (Integer) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(Integer value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_LOGIN using the alias name LastUpdatedLogin.
     * @return the LAST_UPDATED_LOGIN
     */
    public Number getLastUpdatedLogin() {
        return (Number)getAttributeInternal(LASTUPDATEDLOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_LOGIN using the alias name LastUpdatedLogin.
     * @param value value to set the LAST_UPDATED_LOGIN
     */
    public void setLastUpdatedLogin(Number value) {
        setAttributeInternal(LASTUPDATEDLOGIN, value);
    }

    /**
     * Gets the attribute value for RETRUN_FLAG using the alias name RetrunFlag.
     * @return the RETRUN_FLAG
     */
    public String getRetrunFlag() {
        return (String) getAttributeInternal(RETRUNFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for RETRUN_FLAG using the alias name RetrunFlag.
     * @param value value to set the RETRUN_FLAG
     */
    public void setRetrunFlag(String value) {
        setAttributeInternal(RETRUNFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectedRow.
     * @return the SelectedRow
     */
    public Boolean getSelectedRow() {
        return (Boolean) getAttributeInternal(SELECTEDROW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectedRow.
     * @param value value to set the  SelectedRow
     */
    public void setSelectedRow(Boolean value) {
        setAttributeInternal(SELECTEDROW, value);
    }

    /**
     * Gets the attribute value for REQUEST_STATUS using the alias name RequestStatus.
     * @return the REQUEST_STATUS
     */
    public String getRequestStatus() {
        return (String) getAttributeInternal(REQUESTSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_STATUS using the alias name RequestStatus.
     * @param value value to set the REQUEST_STATUS
     */
    public void setRequestStatus(String value) {
        setAttributeInternal(REQUESTSTATUS, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link PwcOdmGradingWeavingHeadersVO.
     */
    public Row getPwcOdmGradingWeavingHeadersVO() {
        return (Row)getAttributeInternal(PWCODMGRADINGWEAVINGHEADERSVO);
    }

    /**
     * Sets the master-detail link PwcOdmGradingWeavingHeadersVO between this object and <code>value</code>.
     */
    public void setPwcOdmGradingWeavingHeadersVO(Row value) {
        setAttributeInternal(PWCODMGRADINGWEAVINGHEADERSVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PwcOdmGradingWeavingLinesMachineNo1.
     */
    public RowSet getPwcOdmGradingWeavingLinesMachineNo1() {
        return (RowSet)getAttributeInternal(PWCODMGRADINGWEAVINGLINESMACHINENO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
