package model.GradingWeaving.VO;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 17 18:20:34 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcOdmGradingWaveingLinesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PwcOdmGradingWaveingLinesVOImpl() {
    }
    

    @Override
      public void insertRow(Row row) {
          //go to the end of Rowset if it has rows
          Row lastRow = this.last();
          if (lastRow !=null){
               //insert new row at the end and make it current
              int indx = this.getRangeIndexOf(lastRow)+1;
              this.insertRowAtRangeIndex(indx,row);
              this.setCurrentRow(row);
          }else { // empty Rowset
          super.insertRow(row);
          }
          }

    /**
     * Returns the bind variable value for p_org_id.
     * @return bind variable value for p_org_id
     */
    public String getp_org_id() {
        return (String)getNamedWhereClauseParam("p_org_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_org_id.
     * @param value value to bind as p_org_id
     */
    public void setp_org_id(String value) {
        setNamedWhereClauseParam("p_org_id", value);
    }


}
