package model.GradingWeaving.VO;

import java.math.BigDecimal;

import model.GradingWeaving.EO.PwcOdmGradingWeavingHeadersEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 31 15:41:39 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcOdmGradingWeavingHeadersVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Attribute1 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        GdDate {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getGdDate();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setGdDate((Date)value);
            }
        }
        ,
        GdId {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getGdId();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setGdId((Number)value);
            }
        }
        ,
        GdNo {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getGdNo();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setGdNo((String)value);
            }
        }
        ,
        ItemCode {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getItemCode();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setItemCode((String)value);
            }
        }
        ,
        ItemDescription {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getItemDescription();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setItemDescription((String)value);
            }
        }
        ,
        ItemId {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getItemId();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setItemId((Number)value);
            }
        }
        ,
        Job {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getJob();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setJob((String)value);
            }
        }
        ,
        JobQuantity {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getJobQuantity();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setJobQuantity((Number)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        LastUpdatedLogin {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getLastUpdatedLogin();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setLastUpdatedLogin((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        QtyReceivedLooming {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getQtyReceivedLooming();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setQtyReceivedLooming((Number)value);
            }
        }
        ,
        SalesOrderNumber {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getSalesOrderNumber();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setSalesOrderNumber((Number)value);
            }
        }
        ,
        SalesOrderHeaderId {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getSalesOrderHeaderId();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setSalesOrderHeaderId((BigDecimal)value);
            }
        }
        ,
        SUMTOTQTY {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getSUMTOTQTY();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setSUMTOTQTY((Number)value);
            }
        }
        ,
        SumGradea {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getSumGradea();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setSumGradea((Number)value);
            }
        }
        ,
        SumGradeb {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getSumGradeb();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setSumGradeb((Number)value);
            }
        }
        ,
        SumGradec {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getSumGradec();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setSumGradec((Number)value);
            }
        }
        ,
        SumGraded {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getSumGraded();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setSumGraded((Number)value);
            }
        }
        ,
        SumGradeD20Above {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getSumGradeD20Above();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setSumGradeD20Above((Number)value);
            }
        }
        ,
        SumGradeD0to1 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getSumGradeD0to1();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setSumGradeD0to1((Number)value);
            }
        }
        ,
        SumGradeD1to5 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getSumGradeD1to5();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setSumGradeD1to5((Number)value);
            }
        }
        ,
        SumGradeD6to19 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getSumGradeD6to19();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setSumGradeD6to19((Number)value);
            }
        }
        ,
        SalesOrderGdNo {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getSalesOrderGdNo();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setSalesOrderGdNo((String)value);
            }
        }
        ,
        JobId {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getJobId();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setJobId((BigDecimal)value);
            }
        }
        ,
        PwcOdmGradingWaveingLinesVO {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getPwcOdmGradingWaveingLinesVO();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PwcOdmGradingWeavingHeadersGdNo1 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getPwcOdmGradingWeavingHeadersGdNo1();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PwcOdmGradingWeavingHeadersSaleOrderNo1 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getPwcOdmGradingWeavingHeadersSaleOrderNo1();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PwcOdmGradingWeavingHeadersItemCode1 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getPwcOdmGradingWeavingHeadersItemCode1();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PwcOdmGradingWeavingHeadersJob1 {
            public Object get(PwcOdmGradingWeavingHeadersVORowImpl obj) {
                return obj.getPwcOdmGradingWeavingHeadersJob1();
            }

            public void put(PwcOdmGradingWeavingHeadersVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PwcOdmGradingWeavingHeadersVORowImpl object);

        public abstract void put(PwcOdmGradingWeavingHeadersVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int GDDATE = AttributesEnum.GdDate.index();
    public static final int GDID = AttributesEnum.GdId.index();
    public static final int GDNO = AttributesEnum.GdNo.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int ITEMDESCRIPTION = AttributesEnum.ItemDescription.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int JOB = AttributesEnum.Job.index();
    public static final int JOBQUANTITY = AttributesEnum.JobQuantity.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int LASTUPDATEDLOGIN = AttributesEnum.LastUpdatedLogin.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int QTYRECEIVEDLOOMING = AttributesEnum.QtyReceivedLooming.index();
    public static final int SALESORDERNUMBER = AttributesEnum.SalesOrderNumber.index();
    public static final int SALESORDERHEADERID = AttributesEnum.SalesOrderHeaderId.index();
    public static final int SUMTOTQTY = AttributesEnum.SUMTOTQTY.index();
    public static final int SUMGRADEA = AttributesEnum.SumGradea.index();
    public static final int SUMGRADEB = AttributesEnum.SumGradeb.index();
    public static final int SUMGRADEC = AttributesEnum.SumGradec.index();
    public static final int SUMGRADED = AttributesEnum.SumGraded.index();
    public static final int SUMGRADED20ABOVE = AttributesEnum.SumGradeD20Above.index();
    public static final int SUMGRADED0TO1 = AttributesEnum.SumGradeD0to1.index();
    public static final int SUMGRADED1TO5 = AttributesEnum.SumGradeD1to5.index();
    public static final int SUMGRADED6TO19 = AttributesEnum.SumGradeD6to19.index();
    public static final int SALESORDERGDNO = AttributesEnum.SalesOrderGdNo.index();
    public static final int JOBID = AttributesEnum.JobId.index();
    public static final int PWCODMGRADINGWAVEINGLINESVO = AttributesEnum.PwcOdmGradingWaveingLinesVO.index();
    public static final int PWCODMGRADINGWEAVINGHEADERSGDNO1 = AttributesEnum.PwcOdmGradingWeavingHeadersGdNo1.index();
    public static final int PWCODMGRADINGWEAVINGHEADERSSALEORDERNO1 = AttributesEnum.PwcOdmGradingWeavingHeadersSaleOrderNo1.index();
    public static final int PWCODMGRADINGWEAVINGHEADERSITEMCODE1 = AttributesEnum.PwcOdmGradingWeavingHeadersItemCode1.index();
    public static final int PWCODMGRADINGWEAVINGHEADERSJOB1 = AttributesEnum.PwcOdmGradingWeavingHeadersJob1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PwcOdmGradingWeavingHeadersVORowImpl() {
    }

    /**
     * Gets PwcOdmGradingWeavingHeadersE1 entity object.
     * @return the PwcOdmGradingWeavingHeadersE1
     */
    public PwcOdmGradingWeavingHeadersEOImpl getPwcOdmGradingWeavingHeadersE1() {
        return (PwcOdmGradingWeavingHeadersEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for GD_DATE using the alias name GdDate.
     * @return the GD_DATE
     */
    public Date getGdDate() {
        return (Date)getAttributeInternal(GDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GD_DATE using the alias name GdDate.
     * @param value value to set the GD_DATE
     */
    public void setGdDate(Date value) {
        setAttributeInternal(GDDATE, value);
    }

    /**
     * Gets the attribute value for GD_ID using the alias name GdId.
     * @return the GD_ID
     */
    public Number getGdId() {
        return (Number)getAttributeInternal(GDID);
    }

    /**
     * Sets <code>value</code> as attribute value for GD_ID using the alias name GdId.
     * @param value value to set the GD_ID
     */
    public void setGdId(Number value) {
        setAttributeInternal(GDID, value);
    }

    /**
     * Gets the attribute value for GD_NO using the alias name GdNo.
     * @return the GD_NO
     */
    public String getGdNo() {
        return (String) getAttributeInternal(GDNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GD_NO using the alias name GdNo.
     * @param value value to set the GD_NO
     */
    public void setGdNo(String value) {
        setAttributeInternal(GDNO, value);
    }

    /**
     * Gets the attribute value for ITEM_CODE using the alias name ItemCode.
     * @return the ITEM_CODE
     */
    public String getItemCode() {
        return (String) getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_CODE using the alias name ItemCode.
     * @param value value to set the ITEM_CODE
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for ITEM_DESCRIPTION using the alias name ItemDescription.
     * @return the ITEM_DESCRIPTION
     */
    public String getItemDescription() {
        return (String) getAttributeInternal(ITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_DESCRIPTION using the alias name ItemDescription.
     * @param value value to set the ITEM_DESCRIPTION
     */
    public void setItemDescription(String value) {
        setAttributeInternal(ITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ITEM_ID using the alias name ItemId.
     * @return the ITEM_ID
     */
    public Number getItemId() {
        return (Number)getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_ID using the alias name ItemId.
     * @param value value to set the ITEM_ID
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for JOB using the alias name Job.
     * @return the JOB
     */
    public String getJob() {
        return (String) getAttributeInternal(JOB);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB using the alias name Job.
     * @param value value to set the JOB
     */
    public void setJob(String value) {
        setAttributeInternal(JOB, value);
    }

    /**
     * Gets the attribute value for JOB_QUANTITY using the alias name JobQuantity.
     * @return the JOB_QUANTITY
     */
    public Number getJobQuantity() {
        return (Number)getAttributeInternal(JOBQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_QUANTITY using the alias name JobQuantity.
     * @param value value to set the JOB_QUANTITY
     */
    public void setJobQuantity(Number value) {
        setAttributeInternal(JOBQUANTITY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_LOGIN using the alias name LastUpdatedLogin.
     * @return the LAST_UPDATED_LOGIN
     */
    public Number getLastUpdatedLogin() {
        return (Number)getAttributeInternal(LASTUPDATEDLOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_LOGIN using the alias name LastUpdatedLogin.
     * @param value value to set the LAST_UPDATED_LOGIN
     */
    public void setLastUpdatedLogin(Number value) {
        setAttributeInternal(LASTUPDATEDLOGIN, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for QTY_RECEIVED_LOOMING using the alias name QtyReceivedLooming.
     * @return the QTY_RECEIVED_LOOMING
     */
    public Number getQtyReceivedLooming() {
        return (Number)getAttributeInternal(QTYRECEIVEDLOOMING);
    }

    /**
     * Sets <code>value</code> as attribute value for QTY_RECEIVED_LOOMING using the alias name QtyReceivedLooming.
     * @param value value to set the QTY_RECEIVED_LOOMING
     */
    public void setQtyReceivedLooming(Number value) {
        setAttributeInternal(QTYRECEIVEDLOOMING, value);
    }

    /**
     * Gets the attribute value for SALES_ORDER_NUMBER using the alias name SalesOrderNumber.
     * @return the SALES_ORDER_NUMBER
     */
    public Number getSalesOrderNumber() {
        return (Number)getAttributeInternal(SALESORDERNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SALES_ORDER_NUMBER using the alias name SalesOrderNumber.
     * @param value value to set the SALES_ORDER_NUMBER
     */
    public void setSalesOrderNumber(Number value) {
        setAttributeInternal(SALESORDERNUMBER, value);
    }

    /**
     * Gets the attribute value for SALES_ORDER_HEADER_ID using the alias name SalesOrderHeaderId.
     * @return the SALES_ORDER_HEADER_ID
     */
    public BigDecimal getSalesOrderHeaderId() {
        return (BigDecimal) getAttributeInternal(SALESORDERHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALES_ORDER_HEADER_ID using the alias name SalesOrderHeaderId.
     * @param value value to set the SALES_ORDER_HEADER_ID
     */
    public void setSalesOrderHeaderId(BigDecimal value) {
        setAttributeInternal(SALESORDERHEADERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SUMTOTQTY.
     * @return the SUMTOTQTY
     */
    public Number getSUMTOTQTY() {
        return (Number)getAttributeInternal(SUMTOTQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SUMTOTQTY.
     * @param value value to set the  SUMTOTQTY
     */
    public void setSUMTOTQTY(Number value) {
        setAttributeInternal(SUMTOTQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumGradea.
     * @return the SumGradea
     */
    public Number getSumGradea() {
        return (Number)getAttributeInternal(SUMGRADEA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumGradea.
     * @param value value to set the  SumGradea
     */
    public void setSumGradea(Number value) {
        setAttributeInternal(SUMGRADEA, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumGradeb.
     * @return the SumGradeb
     */
    public Number getSumGradeb() {
        return (Number)getAttributeInternal(SUMGRADEB);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumGradeb.
     * @param value value to set the  SumGradeb
     */
    public void setSumGradeb(Number value) {
        setAttributeInternal(SUMGRADEB, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumGradec.
     * @return the SumGradec
     */
    public Number getSumGradec() {
        return (Number)getAttributeInternal(SUMGRADEC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumGradec.
     * @param value value to set the  SumGradec
     */
    public void setSumGradec(Number value) {
        setAttributeInternal(SUMGRADEC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumGraded.
     * @return the SumGraded
     */
    public Number getSumGraded() {
        return (Number)getAttributeInternal(SUMGRADED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumGraded.
     * @param value value to set the  SumGraded
     */
    public void setSumGraded(Number value) {
        setAttributeInternal(SUMGRADED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumGradeD20Above.
     * @return the SumGradeD20Above
     */
    public Number getSumGradeD20Above() {
        return (Number)getAttributeInternal(SUMGRADED20ABOVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumGradeD20Above.
     * @param value value to set the  SumGradeD20Above
     */
    public void setSumGradeD20Above(Number value) {
        setAttributeInternal(SUMGRADED20ABOVE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumGradeD0to1.
     * @return the SumGradeD0to1
     */
    public Number getSumGradeD0to1() {
        return (Number)getAttributeInternal(SUMGRADED0TO1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumGradeD0to1.
     * @param value value to set the  SumGradeD0to1
     */
    public void setSumGradeD0to1(Number value) {
        setAttributeInternal(SUMGRADED0TO1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumGradeD1to5.
     * @return the SumGradeD1to5
     */
    public Number getSumGradeD1to5() {
        return (Number)getAttributeInternal(SUMGRADED1TO5);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumGradeD1to5.
     * @param value value to set the  SumGradeD1to5
     */
    public void setSumGradeD1to5(Number value) {
        setAttributeInternal(SUMGRADED1TO5, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumGradeD6to19.
     * @return the SumGradeD6to19
     */
    public Number getSumGradeD6to19() {
        return (Number)getAttributeInternal(SUMGRADED6TO19);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumGradeD6to19.
     * @param value value to set the  SumGradeD6to19
     */
    public void setSumGradeD6to19(Number value) {
        setAttributeInternal(SUMGRADED6TO19, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SalesOrderGdNo.
     * @return the SalesOrderGdNo
     */
    public String getSalesOrderGdNo() {
        return (String) getAttributeInternal(SALESORDERGDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SalesOrderGdNo.
     * @param value value to set the  SalesOrderGdNo
     */
    public void setSalesOrderGdNo(String value) {
        setAttributeInternal(SALESORDERGDNO, value);
    }

    /**
     * Gets the attribute value for JOB_ID using the alias name JobId.
     * @return the JOB_ID
     */
    public BigDecimal getJobId() {
        return (BigDecimal) getAttributeInternal(JOBID);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_ID using the alias name JobId.
     * @param value value to set the JOB_ID
     */
    public void setJobId(BigDecimal value) {
        setAttributeInternal(JOBID, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PwcOdmGradingWaveingLinesVO.
     */
    public RowIterator getPwcOdmGradingWaveingLinesVO() {
        return (RowIterator)getAttributeInternal(PWCODMGRADINGWAVEINGLINESVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PwcOdmGradingWeavingHeadersGdNo1.
     */
    public RowSet getPwcOdmGradingWeavingHeadersGdNo1() {
        return (RowSet)getAttributeInternal(PWCODMGRADINGWEAVINGHEADERSGDNO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PwcOdmGradingWeavingHeadersSaleOrderNo1.
     */
    public RowSet getPwcOdmGradingWeavingHeadersSaleOrderNo1() {
        return (RowSet)getAttributeInternal(PWCODMGRADINGWEAVINGHEADERSSALEORDERNO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PwcOdmGradingWeavingHeadersItemCode1.
     */
    public RowSet getPwcOdmGradingWeavingHeadersItemCode1() {
        return (RowSet)getAttributeInternal(PWCODMGRADINGWEAVINGHEADERSITEMCODE1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PwcOdmGradingWeavingHeadersJob1.
     */
    public RowSet getPwcOdmGradingWeavingHeadersJob1() {
        return (RowSet)getAttributeInternal(PWCODMGRADINGWEAVINGHEADERSJOB1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
