CREATE TABLE PWC_ODM_BREAK_DOWN_HDR 
(
  HEADER_ID NUMBER 
, GD_NUMBER VARCHAR2(255 BYTE) 
, SALE_ORDER_NUMBER NUMBER 
, ITEM_ID NUMBER 
, ORG_ID NUMBER 
, CONSTRACTION_1 VARCHAR2(255 BYTE) 
, CONTRACTION_2 VARCHAR2(255 BYTE) 
, CONTRACTION_3 NUMBER 
, CONTRACTION_4 NUMBER 
, GREIGE_WIDTH NUMBER 
, FINISH_WIDTH NUMBER 
, WEAVE VARCHAR2(255 BYTE) 
, FEBRIC_PROCESS VARCHAR2(255 BYTE) 
, ORDER_QTY_YDS NUMBER 
, ORDER_QTY_MTR NUMBER 
, LAST_DELIVERY_DATE DATE 
, BLEND VARCHAR2(255 BYTE) 
, PROCESS_LOSS NUMBER 
, BEAM_WIDTH VARCHAR2(20 BYTE) 
, LOOM_TYPE VARCHAR2(255 BYTE) 
, BEAM_DIA_MM NUMBER 
, REQ_SIZE_LENGTH NUMBER 
, NUMBER_BEAM NUMBER 
, WT_OF_WARP NUMBER 
, TOTAL_ENDS NUMBER 
, WARPING_START_DATE DATE 
, WARP_YARN_COUNT NUMBER 
, YARN_BRAND VARCHAR2(255 BYTE) 
, YARN_LOT VARCHAR2(255 BYTE) 
, YARN_TYPE VARCHAR2(255 BYTE) 
, YARN_BLEND VARCHAR2(255 BYTE) 
, BEAM_LENGTH VARCHAR2(20 BYTE) 
, TOTAL_WARP_REQ NUMBER 
, WARPING_FINISHING_DATE DATE 
, DROPPER_THICKNESS_MM NUMBER 
, GREY_EPI_WEAVING NUMBER 
, REED_COUNT NUMBER 
, END_DENT NUMBER 
, SELVEDGE_ENDS_BOTH_SIDES NUMBER 
, SELVEDGE_SIZE NUMBER 
, PLAN_LOOM NUMBER 
, WEFT_COUNT NUMBER 
, WEFT_YARN_TYPE VARCHAR2(255 BYTE) 
, WT_OF_WEFT_YARN NUMBER 
, WEAVE_FINISHING_DATE DATE 
, TOTAL_WEAVABLE_LENGTH NUMBER 
, SELVEDGE_ENDS NUMBER 
, GREY_PPI_WEAVING NUMBER 
, GREY_WIDTH_WEAVING NUMBER 
, REED_SPACE_INCH NUMBER 
, SELVEDGE_ENDS_DENT NUMBER 
, LOOM_RPM NUMBER 
, LOOM_START_DATE DATE 
, TOTAL_PROD_PER_DAY NUMBER 
, LOOM_PROD_PER_DAY NUMBER 
, WEFT_YARN_BRAND VARCHAR2(255 BYTE) 
, WEFT_YARN_BLEND VARCHAR2(255 BYTE) 
, TOTAL_WEFT_REQ NUMBER 
, DAY_REQ_TO_FINISH NUMBER 
, GREY_EPI_TABLE NUMBER 
, GREY_WIDTH_FOLDING NUMBER 
, GREY_WIDTH_TABLE VARCHAR2(20 BYTE) 
, GREY_GSM NUMBER 
, REQ_FOLDING_PROD_DAY NUMBER 
, GREY_PPI_TABLE NUMBER 
, GREY_FAB_WT NUMBER 
, INSPECTION_FINISHED_DATE DATE 
, TOTAL_YARN_REQ NUMBER 
, TOTAL_YARN_ALLOCATED NUMBER 
, REMAINING_YARN_REQ NUMBER 
, TOTAL_YARN_AVAILABLE NUMBER 
, YARN_PURCHASE_REQ NUMBER 
, PILE_YARN_COUNT VARCHAR2(255 BYTE) 
, PILE_YARN_BRAND VARCHAR2(255 BYTE) 
, PILE_YARN_ENDS_INCH NUMBER 
, TOTAL_PILE_YARN_ENDS NUMBER 
, SPLITS NUMBER 
, SIZE_TERRY NUMBER 
, DESIGN VARCHAR2(255 BYTE) 
, WEIGHT_PILE_YARN NUMBER 
, TOTAL_PILE_YARN_REQ NUMBER 
, LAST_UPDATE_DATE DATE 
, LAST_UPDATED_BY NUMBER 
, CREATION_DATE DATE 
, CREATED_BY NUMBER 
, LAST_UPDATE_LOGIN NUMBER 
, ATTRIBUTE1 VARCHAR2(255 BYTE) 
, ATTRIBUTE2 VARCHAR2(255 BYTE) 
, ATTRIBUTE3 VARCHAR2(255 BYTE) 
, ATTRIBUTE4 VARCHAR2(255 BYTE) 
, ATTRIBUTE5 VARCHAR2(255 BYTE) 
, ATTRIBUTE6 VARCHAR2(255 BYTE) 
, ATTRIBUTE7 VARCHAR2(255 BYTE) 
, ATTRIBUTE8 VARCHAR2(255 BYTE) 
, ATTRIBUTE9 VARCHAR2(255 BYTE) 
, ATTRIBUTE10 VARCHAR2(255 BYTE) 
, ATTRIBUTE11 VARCHAR2(255 BYTE) 
, ATTRIBUTE12 VARCHAR2(255 BYTE) 
, ATTRIBUTE13 VARCHAR2(255 BYTE) 
, ATTRIBUTE14 VARCHAR2(255 BYTE) 
, ATTRIBUTE15 VARCHAR2(255 BYTE) 
, C_W_PER NUMBER 
, "LOOM_EFFICIENCY " NUMBER 
) 
LOGGING 
TABLESPACE "APPS_TS_TX_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 131072 
  NEXT 131072 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
);
